language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
#  - 7.2 # TODO: Add it after upgrade to latest Laravel version

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - sudo redis-server /etc/redis/redis.conf --port 6379

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist --verbose
